---
apiVersion: infrastructure.cluster.x-k8s.io/{{ .Values.clusterapiVersion }}
kind: VSphereCluster
metadata:
  name: {{ include "capi-vsphere.name" . }}
spec:
  controlPlaneEndpoint:
    host: {{ required ".Values.vsphere.controlPlaneEndpoint.host" .Values.vsphere.controlPlaneEndpoint.host }}
    port: {{ required ".Values.vsphere.controlPlaneEndpoint.port" .Values.vsphere.controlPlaneEndpoint.port }}
  identityRef:
    kind: Secret
    name: {{ include "capi-vsphere.cloudConfigSecretName" . }}
  server: {{ required ".Values.vsphere.server is required" .Values.vsphere.server }}
  thumbprint: {{ .Values.vsphere.thumbprint }}
